[package]
name = "lez-rln-ffi"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["rlib", "cdylib", "staticlib"]

[dependencies]
rln-layouts = { path = "../rln-layouts" }
rln = "2.0.1"
sha2 = "0.10"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
risc0-zkvm = { version = "3.0", default-features = false, features = ["std"] }

[build-dependencies]
cbindgen = "0.29"
