language = "C"
include_guard = "LEZ_RLN_FFI_H"

[export]
include = ["Error", "RlnMerkleProof", "RLN_TREE_DEPTH", "MerkleProofsPlan", "SubtreeEntry", "MAX_SUBTREES_PER_CALL"]
prefix = "RlnFfi"

[enum]
rename_variants = "ScreamingSnakeCase"
prefix_with_name = true

[fn]
rename_args = "None"
